Document: limes-service
Title: Debian limes-service Manual
Author: <insert document author here>
Abstract: This manual describes what limes-service is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/limes-service/limes-service.sgml.gz

Format: postscript
Files: /usr/share/doc/limes-service/limes-service.ps.gz

Format: text
Files: /usr/share/doc/limes-service/limes-service.text.gz

Format: HTML
Index: /usr/share/doc/limes-service/html/index.html
Files: /usr/share/doc/limes-service/html/*.html
